### ISSUE TITLE
Release 0.3?

### ISSUE THREAD

**Issue by stuarteberg** [dask/dask-image#129]
Looks like there have been various bugfixes and improvements since the last release.  Perhaps the most interesting one is the new distributed implementation of `ndmeasure.label()` from @jni and @jakirkham (#94).

Is it time for a new release?  I suppose you'll want to bump straight to 0.3, since Python 2.7 has been dropped (#119).

**Comment by GenevieveBuckley** [comment]
It might be, @jakirkham what's your feeling? I'd be happy to learn the release process and make notes to add to the docs.

Maybe we can sneak https://github.com/dask/dask-image/pull/112 into this one too

**Comment by jni** [comment]
Ping @jakirkham 

Also feel free to grant @GenevieveBuckley and I (and @stuarteberg!) access rights for PyPI if, as I suspect, you are too busy with NVIDIA-y things to continue maintaining this!

**Comment by leifdenby** [comment]
I would be happy to help with this too. `dask_image.ndmeasure.area` has been added since `0.2` too which is really great(!)

If the versioning is following semver would changing the argument `labels`  to `label_image` in the `dask_image.ndmeasure` functions be considered a breaking a change and warrant making the next version `1.0.0`? Sorry if I've missed discussion on this. This library has saved me a lot of time, so I'd like to contribute back if I can

**Comment by GenevieveBuckley** [comment]
This still needs followup, the bottleneck here is the ability to upload to PyPI. 

If you're more comfortable with it @jakirkham, we could use [Github secrets](https://github.com/dask/dask-image/settings/secrets) to tie those credentials to this repository, and then use github actions to automate the build/release. I don't have access to the [conda feedstock](https://github.com/conda-forge/dask-image-feedstock), but I think that should just update itself automatically after a successful PyPI release?

I'm happy to do the legwork on [setting up a github action for this](https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/). Thanks to Kira, napari have just set up the same thing, so we could use that as a model here: https://github.com/napari/napari/blob/master/.github/workflows/make_release.yml

**Comment by jni** [comment]
@leifdenby 

> considered a breaking a change and warrant making the next version 1.0.0

Note that in semver, everything is fair game in the 0.x series. =) Typically, packages in the SciPy stack have allowed breaking changes between minor versions in early 0.x releases (with or without warnings, depending on the maturity of the library).

**Comment by jakirkham** [comment]
What’s your PyPI username @GenevieveBuckley ? Maybe I can just give you permissions there 🙂

**Comment by GenevieveBuckley** [comment]
> 
> 
> What’s your PyPI username @GenevieveBuckley ? Maybe I can just give you permissions there 🙂

Username on PyPI & TestPyPI is @GenevieveBuckley, same as here. 

Does it make sense to also grant permissions fo https://github.com/conda-forge/dask-image-feedstock? (I hope I never need to touch the conda feedstock, tbh)

**Comment by jakirkham** [comment]
Thanks! Added to PyPI.

Sure that sounds like a good idea. Do you want to send a PR to add yourself over there?

**Comment by GenevieveBuckley** [comment]
> Do you want to send a PR to add yourself over there?

Over where, sorry?

**Comment by GenevieveBuckley** [comment]
FYI: I've pulled over some of the machinery/settings napari use for their automated releases, that's over on [this branch](https://github.com/GenevieveBuckley/dask-image/tree/automate-releases) for now. I'm planning to make a mess of things over on TestPyPI until I get the hang of it, so there might be a delay there.

**Comment by jakirkham** [comment]
>> Do you want to send a PR to add yourself over there?
>
> Over where, sorry?

Sorry. Skipped quoting the previous comment for simplicity. Was responding to this question...

> Does it make sense to also grant permissions to https://github.com/conda-forge/dask-image-feedstock?

If you send a PR to add yourself over there, I'll happily merge :)

**Comment by GenevieveBuckley** [comment]
FYI, I'm going to try and get a release candidate (`v0.3.0rc1`) out in the next 1-2 days.

**Comment by jakirkham** [comment]
Sounds good 🙂

Have submitted PR ( https://github.com/conda-forge/dask-image-feedstock/pull/4 ) to give you permissions on the feedstock.

**Comment by GenevieveBuckley** [comment]
Ok, the release candidate on PyPI seems to be working well, so I'm going to go ahead and release v0.3.0

I *think* that means regro-cf-autotick-bot will pick that up and update our conda-forge repository. (The bot didn't do this for the release candidate, but that might be by design). In any case, if the conda-forge stuff doesn't work for me first try, you can walk me through it & we'll put out a patch release if we have to.

**Comment by jakirkham** [comment]
Yeah we decided to disable RCs with the conda-forge bot.

It seems to have picked it up ( https://github.com/conda-forge/dask-image-feedstock/pull/5 ). We should double check the dependencies though as the bot doesn’t currently update them.

**Comment by GenevieveBuckley** [comment]
Yeah, I think we do have a problem with the dependencies in general, not just on conda forge. 

Sorry for not picking up on this earlier (didn't try `imread` specifically, but clearly I should have), but I think maybe we need to add dependencies so pims will consistently work:
* imageio
* tifffile
* jpype (mind you pims still might not work for all files even if we have this, when I try opening a deltavision `.dv` file with `pims.Open` it doesn't try the bioformats reader it just says it can't auto-detect the file type)

I can add these to out setup.py file

**Comment by jakirkham** [comment]
Yeah you’re right. I’d forgotten how this works. Those were optional dependencies. Though maybe it is worth making them hard dependencies either for dask-image or pims (with help from others).

**Comment by GenevieveBuckley** [comment]
Also, it seems if we use any recent version of `imageio`, pims forces us to also install `imageio-ffmpeg` which is [around 60MiB](https://pypi.org/project/imageio-ffmpeg/#description). I think we'll just have to go with it, the alternatives for basic image reading in pims are either `scikit-image` or `matplotlib` & that's not any better.

**Comment by jakirkham** [comment]
Well `tifffile` was dropped from `scikit-image`. ( https://github.com/scikit-image/scikit-image/pull/4235 )

**Comment by GenevieveBuckley** [comment]
Ok then. Unless you object, I think we should make these required dependencies for `dask-image` (being able to load/open images seems like a high priority to me, since it's one of the first things a new user will try to do):
* `tifffile`
* `imageio`
* `imageio-ffmpeg`
* `jpype`

I'll also make sure to update the test to import `tifffile` directly, not the old scikit-image vendored version.

**Comment by GenevieveBuckley** [comment]
Release 0.3.0 of dask-image is now available on PyPI and conda-forge (install with pip or conda).

**Comment by jakirkham** [comment]
Being able to open images is important. However having a simple install is important too. I don’t think we should add too many dependencies (particularly if those dependencies are large or require other languages to function). Also it would be good to maintain a permissive license when adding dependencies. Things like `tifffile` or `imageio` seem ok. Requiring Java or FFMPEG seem a bit too heavy weight.

**Comment by GenevieveBuckley** [comment]
Disagreement is welcome and encouraged!

I do agree with you about `imageio-ffmpeg`. It might be possible to get pims to shift that import into the video loader instead of the imageio sequence reader, which would remove our concern.

I'm not so sure about `jpype`, I didn't think it was that heavyweight? I'm not sure how it works though, I don't think it bundles java but maybe expects to find java already on your system. I guessed based on eyeballing [these filesize numbers](https://pypi.org/project/JPype1/0.7.5/#files) vs comparable [imageio numbers](https://pypi.org/project/imageio/#files)

**Comment by jakirkham** [comment]
`jpype` doesn't bundle Java, but it does require a working Java install on your system. There can be some fiddling required to get that to work with a Java install. In general would like to avoid the associated maintenance burden if possible by leaving it optional.

**Comment by GenevieveBuckley** [comment]
Sounds fair
