### ISSUE TITLE
Not able to map actual image name with dask_image.imread

### ISSUE THREAD

**Issue by satish-madugula** [dask/dask-image#200]
Not able to get the respective filename by using dask-image.

```
import glob
import cv2
from dask_image import imread as imr

img_names = glob.glob(r'D:\dataset2\*.jpg')
imgs = imr.imread(r'D:\dataset2\*.jpg',arraytype='numpy')

print(img_names[124])  
cv2.imshow(img_names[124],imgs[124].compute())
cv2.waitKey(0)
cv2.destroyAllWindows()

```

For example:
    img_names[124]  is actually 'abc.jpg'
    imgs[124].compute() loads gives me 'xyz.jpg'

also tried using  **sorted(glob.glob(r'D:\dataset2\\*.jpg'))**

- Dask version: 0.5.0
- Python version:3.7
- Operating System: windows 10
- Install method : pip

**Comment by GenevieveBuckley** [comment]
Hi @satish-madugula, I can't reproduce the behaviour you're describing here, so it's hard to know what might be going on.

1. Which version of the `pims` library are you using?
2. Can you try this with `dask-image` installed from the master branch, like this:
```
python -m pip install git+https://github.com/dask/dask-image.git
```

I make this second suggestion because there was a recent change that added an explicit sort to the filename glob:
https://github.com/dask/dask-image/blob/63543bf2f6553a8150f45289492bf614e1945ac0/dask_image/imread/__init__.py#L76

I'm not sure if that would make a difference, because `pims` should already be doing that for you, and I don't see any strange behaviour when I try `dask-image=0.5.0` (I'm on Linux instead of Windows though).

**Comment by satish-madugula** [comment]
Hi @GenevieveBuckley 

Thanks for the response, it is working after installing dask-image using master branch.

`python -m pip install git+https://github.com/dask/dask-image.git`

**Comment by GenevieveBuckley** [comment]
Hm, interesting. We've been intending to make a new release, so I think I should do that sooner rather than later given the bug you've described.

Thank you for the report!
