### ISSUE TITLE
Publish .whl to PyPI

### ISSUE THREAD

**Issue by thewtex** [dask/dask-image#271]
Hi @GenevieveBuckley @jakirkham ,

Another humble request :pray: -- We are trying to use dask-image in Pyodide / JupyterLite and its needs the `*.whl` file. Could this please be published to PyPI? It looks like there is only the sdist now.  It can be generated with, for example `cd ~/src/dask-image; pip wheel .`

Thank you!

CC: @bnmajor

**Comment by jakirkham** [comment]
Think this would just be a matter of updating this line. Maybe an easy PR for someone? 😉

https://github.com/dask/dask-image/blob/b8ff7d9d370750a0074cd7d973329f79669fbc05/.github/workflows/python-publish.yml#L30

**Comment by thewtex** [comment]
> Think this would just be a matter of updating this line.

:eyes: 

> Maybe an easy PR for someone? 

:raising_hand: #272 

:-)

**Comment by jakirkham** [comment]
Thanks Matt! 🙏

Now that is in we should be good to do this as part of the next release.

**Comment by thewtex** [comment]
Thank you, John!

**Comment by jakirkham** [comment]
@GenevieveBuckley, do you recall what we need to do to create a new release?

**Comment by GenevieveBuckley** [comment]
The release guide is here: https://github.com/dask/dask-image/blob/main/docs/release/release_guide.rst

If you notice anything that needs to be updated in that doc, feel free to edit it. (I think the only thing we don't really do is make release candidates, mostly because we don't really have people available to test them, so no need to make the process longer than it has to be)

**Comment by GenevieveBuckley** [comment]
[Release 2023.03.0](https://github.com/dask/dask-image/releases/tag/v2023.03.0) of dask-image is now available, and the .whl files [are now uploaded to PyPI](https://pypi.org/project/dask-image/#history).

Let us know if you need anything else, Matt.
